kind: Pod
metadata:
  name: git, maven and kaniko
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "build-linux"
      effect: "NoSchedule"
  containers:
  - name: maven
    image: maven:3.6.3-jdk-8
    command:
    - bash
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: registrykey  # pre-requisite
          items:
          - key: .dockerconfigjson
            path: config.json
