name: markdown-link-check

on:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    name: Check markdown files for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          config_file: '.github/workflows/markdown.links.config.json'
          debug: true
          search_paths: |
            docs/CBCI-Pipeline.md